### ISSUE TITLE
My mpv is a bit slower than yours so it fails on startup.

### ISSUE THREAD

**Issue by choffee** [slashformotion/radioboat#3]
I had to increace the sleep to 200ms to wait for mpv to create the pipe on my machine.

Maybe it could loop a couple of times on the sleep so it's quick for most but will wait if needed.

**Comment by slashformotion** [comment]
I could increase the delay to 400 ms with no complains from users. It would be acceptable as a momentary fix.
I will search if there is a way to wait and retry to connect on "timout"

**Comment by slashformotion** [comment]
@choffee I've a pre-release ready fixing that https://github.com/slashformotion/radioboat/releases/tag/v0.1.1
