### ISSUE TITLE
Version shouldn't be hardcoded

### ISSUE THREAD

**Issue by superherointj** [slashformotion/radioboat#7]
https://github.com/slashformotion/radioboat/blob/master/cmd/root.go#L36

**Comment by slashformotion** [comment]
If I understand correctly you are trying to add radioboat to some build system ?

**Comment by slashformotion** [comment]
*(Note to myself: https://github.com/gohugoio/hugo/blob/72b0ccdb010fcdfeb3bb4a955d4fc04529816c0d/common/hugo/version.go#L136)*

**Comment by superherointj** [comment]
> If I understand correctly you are trying to add radioboat to some build system ?

Nixpkgs is a repository of 'nix packages'. It's part of a Linux distribution called [NixOS](https://nixos.org/)[²](https://intj.com.br/why-nixos.html). But can be used in standalone mode in basically any distro (mac/darwin, debian, arch, etc).
@zendo wanted to publish `radioboat` package. But version was not matching.
